-- CoursePilot initial database schema
--
-- This migration represents the current database structure.
-- Do not run it against the existing Supabase project because
-- these tables and policies already exist there.

-- =========================================================
-- COURSES
-- Stores each golf course using CoursePilot.
-- =========================================================

create table public.courses (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    slug text not null unique,
    created_at timestamptz not null default now()
);

alter table public.courses
enable row level security;

-- No public courses policies exist yet.
-- Course data is currently managed through the Supabase dashboard.


-- =========================================================
-- COURSE MEMBERS
-- Connects authenticated manager accounts to golf courses.
-- =========================================================

create table public.course_members (
    id uuid primary key default gen_random_uuid(),

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    course_id uuid not null
        references public.courses(id)
        on delete cascade,

    role text not null default 'manager',

    created_at timestamptz not null default now(),

    constraint course_members_user_course_unique
        unique (user_id, course_id),

    constraint course_members_role_check
        check (
            role in (
                'owner',
                'manager',
                'staff'
            )
        )
);

alter table public.course_members
enable row level security;

revoke all
on table public.course_members
from anon, authenticated;

grant select
on table public.course_members
to authenticated;

create policy "Users can view their own course memberships"
on public.course_members
for select
to authenticated
using (
    user_id = (
        select auth.uid()
    )
);


-- =========================================================
-- BOOKINGS
-- Stores tee-time booking requests.
-- =========================================================

create table public.bookings (
    id bigint generated by default as identity
        primary key,

    name text,
    day text,
    time text,
    players text,

    created_at timestamptz
        not null
        default now(),

    status text
        not null
        default 'pending',

    course_id uuid
        not null
        references public.courses(id),

    constraint bookings_status_check
        check (
            status in (
                'pending',
                'confirmed',
                'declined',
                'cancelled'
            )
        )
);

create index bookings_course_id_index
on public.bookings(course_id);

alter table public.bookings
enable row level security;

revoke all
on table public.bookings
from anon, authenticated;

grant insert
on table public.bookings
to anon;

grant select
on table public.bookings
to authenticated;

grant update (status)
on table public.bookings
to authenticated;


-- Public website visitors may submit booking requests.
-- They may not read, edit, or delete bookings.

create policy "Public can submit booking requests"
on public.bookings
for insert
to anon
with check (true);


-- Authenticated course members may only view bookings
-- belonging to one of their assigned golf courses.

create policy "Course members can view their course bookings"
on public.bookings
for select
to authenticated
using (
    exists (
        select 1
        from public.course_members
        where course_members.user_id = (
            select auth.uid()
        )
        and course_members.course_id =
            bookings.course_id
    )
);


-- Authenticated course members may update booking status
-- only for bookings belonging to their assigned courses.
--
-- Column permissions above restrict updates to status only.

create policy "Course members can update booking status"
on public.bookings
for update
to authenticated
using (
    exists (
        select 1
        from public.course_members
        where course_members.user_id = (
            select auth.uid()
        )
        and course_members.course_id =
            bookings.course_id
    )
)
with check (
    exists (
        select 1
        from public.course_members
        where course_members.user_id = (
            select auth.uid()
        )
        and course_members.course_id =
            bookings.course_id
    )
);